// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2a0tRMNycLVU4boTm1Ob1oJCGxMPYzKg',
    appId: '1:424265736340:web:28aabd0a4fe7d5e2751481',
    messagingSenderId: '424265736340',
    projectId: 'hiero-jobseeker',
    authDomain: 'hiero-jobseeker.firebaseapp.com',
    storageBucket: 'hiero-jobseeker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqZB2wD-4GSJnjdkPrF8pUtePybZcxwdc',
    appId: '1:424265736340:android:4d57fd76a2ed0091751481',
    messagingSenderId: '424265736340',
    projectId: 'hiero-jobseeker',
    storageBucket: 'hiero-jobseeker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QSukHwqHk0om4Xfo7RgOq4FOQnKade8',
    appId: '1:424265736340:ios:62b785177f5f7112751481',
    messagingSenderId: '424265736340',
    projectId: 'hiero-jobseeker',
    storageBucket: 'hiero-jobseeker.appspot.com',
    iosBundleId: 'com.example.hieroJobSeeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7QSukHwqHk0om4Xfo7RgOq4FOQnKade8',
    appId: '1:424265736340:ios:62b785177f5f7112751481',
    messagingSenderId: '424265736340',
    projectId: 'hiero-jobseeker',
    storageBucket: 'hiero-jobseeker.appspot.com',
    iosBundleId: 'com.example.hieroJobSeeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2a0tRMNycLVU4boTm1Ob1oJCGxMPYzKg',
    appId: '1:424265736340:web:7be36a13f5bcabc6751481',
    messagingSenderId: '424265736340',
    projectId: 'hiero-jobseeker',
    authDomain: 'hiero-jobseeker.firebaseapp.com',
    storageBucket: 'hiero-jobseeker.appspot.com',
  );
}
